/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5.1/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
}

repositories {
    mavenCentral()

    maven {
        url = uri("https://clojars.org/repo/")
    }
}

dependencies {

    // last LGPL release of itext is version 4.2.0
//  https://mvnrepository.com/artifact/itext/itext
    implementation("itext:itext:4.2.0")
}

